### ISSUE TITLE
Support for multiple calls to the same function

### ISSUE THREAD

**Issue by rjmackay** [php-mock/php-mock-mockery#6]
There doesn't seem to be able simple way to set up expectations for multiple function calls.

I've ended up doing this as a workaround, but its ugly:
```
$mockFetchBody = PHPMockery::mock("Namespace", "imap_fetchbody");
$mockFetchBody
            ->with('someparams')
            ->andReturn('response');
$mockFetchBody
            ->getMock()
                ->shouldReceive(\phpmock\integration\MockDelegateFunctionBuilder::METHOD)
            ->with('nextparams')
            ->andReturn('response2');
```

**Comment by malkusch** [comment]
> There doesn't seem to be able simple way to set up expectations for multiple function calls.

How would you do that for class methods with Mockery?

**Comment by malkusch** [comment]
I see. I guess the best approach would be `PHPMockery::mock()` returning an interface which exposes an API to add further expectations. So that in your case you could simply call

    $mockFetchBody->shouldReceive()

Help me a bit out, as I'm no Mockery user: I understand that the interface should then expose
everything which could be applied on a method which is:

- allows()
- expects()
- shouldReceive()
- shouldNotReceive()
- shouldHaveReceived()
- shouldNotHaveReceived()

I think this makes much more sense than the current approach. In a first iteration I would add those methods as an additional interface. In the long run I would then remove the old behaviour. Your opinion on that?
